### PR TITLE
Corrected typo and added link to Bryson's PatchServer in comments

### PR DESCRIPTION
**Pull request by krypted**
Corrected typo in line 696 and added link to Bryson's PatchServer in comments when we kick off the patch server post to json

### CODE REVIEW

**Comment by sheagcraig** [comment]
Hello sir,
I pulled this down and made some changes; most of which were style.

The big ones were removing the hardcoded Google Chrome data and rewriting stuff to use curl since we can't easily add requests (back) as a dependency to this project.

A few questions I had:
1. What does a response, both successful and failed, look like from the patch server?
1. As it stands, there's no auth or SSL going on with these posts. I'm guessing that's not how this would work in actual use. So we'll need that in as well.
1. AutoPkg may not necessarily always have BundleID available; or other data like Publisher, minimum operating system, etc. JSS recipes can be updated to extract this data, but then we would need to have a codified way for stashing that information in the AutoPkg environment dictionary. I think this is where the most work is going to have to happen.

I think you should be able to rebase off of my krypted-master branch to get this one up to date with my changes.

**Comment by yuresko** [comment]
Hello,

I am working with Charles on implementing these changes and testing on my servers.  Do you anticipate the Patch Server URL to be hardcoded where you would normally put in your Jamf API creds? Or somewhere in the script?  And too, Bundle ID is not an imminent need, just a nice to have on the Patch Server.

Let me know your thoughts, thanks!

**Comment by sheagcraig** [comment]
Hi @yuresko,
So my expectation would be that the Patch Server URL would be stored in the same preferences file that JSSImporter uses for all of its other settings..

**Comment by grahampugh** [comment]
@yuresko Would it be realistic to think that each patch recipe might point to a different patch server? For instance, many recipes might point to Bryson’s community patch server, but one might need an internal or separate patch server for in-house apps. If so, we will need to specify the URL in the recipe itself.

Also, can this process work without the preamble associated with patch? For example, does it ensure that the patch user agreement has been agreed via the UAPI? Does it create a fresh patch definition object (forgive me if I’m getting the terminology wrong) or does it already need to exist? It would be nice if it worked “out of the box”.

**Comment by grahampugh** [comment]
I suspect this is dead but will leave it here in case and of the authors wish to pursue it,

**Comment by grahampugh** [comment]
Fair to say that this is dead.

**Pull request closed without merging**
